"""
Scene visuals: what fills the screen behind a scene's text.

  stock — a royalty-free video from Pixabay (free; a photo when no video fits), matched by English keywords.
  image — an illustration generated by OpenAI (for what stock can't show, e.g. a tyre in cut-away).
  clip  — a short animated clip generated by Google Veo (the costly kind: key concepts only).

Every kind is optional: a provider without its key is simply not offered, and a scene whose visual can't be
had falls back to the brand background. Files are cached in storage by what was asked (see `cache_path`), so
producing a video again never pays for the same visual twice.
"""

import base64
import binascii
import hashlib
import logging
import re
import subprocess
from contextlib import contextmanager
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from urllib.parse import urljoin, urlsplit

import httpx

from app.core.config import get_settings

logger = logging.getLogger(__name__)

Kind = str  # "stock" | "image" | "clip" | "infographic"
KINDS = ("stock", "image", "clip", "infographic")
PIXABAY = "https://pixabay.com/api"
GEMINI = "https://generativelanguage.googleapis.com/v1beta"
OPENAI_IMAGES = "https://api.openai.com/v1/images/generations"
REQUEST_TIMEOUT_SECONDS = 60
TRANSFER_TIMEOUT_SECONDS = 300
IMAGE_TIMEOUT_SECONDS = 240
CHUNK_BYTES = 1 << 20
MAX_VISUAL_BYTES = 300 * 1024 * 1024  # a stock video or clip larger than this is not worth the disk
MAX_REDIRECTS = 5
GEMINI_HOST = "generativelanguage.googleapis.com"
# Where the providers' files may be downloaded from (their CDNs): anything else is refused.
DOWNLOAD_DOMAINS = ("pixabay.com", "googleapis.com", "googleusercontent.com")
MIN_STOCK_SECONDS = 5
CLIP_SECONDS = 8
# An infographic explains: exact labels in the course's language, the brand's look, and the corner where the
# presenter's bubble goes left empty.
INFOGRAPHIC_STYLE = (
    "Clean, accurate technical infographic for a corporate training course. Dark charcoal background (#111111), flat "
    "vector illustration with precise technical drawings, orange (#ff4c01) highlights, white sans-serif text. "
    "Write every label exactly as given, spelled correctly, large and legible; no other text. Keep the bottom-right "
    "corner (the last 25% of the width and 35% of the height) completely empty. No logos, no watermarks."
)
STYLE = ("Cinematic, realistic, professional training video look, soft natural light. Absolutely no text, letters, "
         "numbers, signs, captions, watermarks, brand names or logos anywhere in the frame.")


class VisualError(RuntimeError):
    """A visual could not be had: the scene tries the next kind, or keeps the brand background.

    `retryable`: the provider is busy (e.g. a rate limit), the same request may work in a while."""

    def __init__(self, message: str, retryable: bool = False):
        super().__init__(message)
        self.retryable = retryable


@dataclass(frozen=True)
class VisualRequest:
    kind: Kind
    query: str  # English keywords for stock
    prompt: str  # English description for generated images and clips (an infographic's, in the course's language)
    variant: int = 0  # "another version" of the same description

    def key(self) -> str:
        """Stable id of what was asked: the same request reuses the same file."""
        text = "\n".join([self.kind, self.query.strip().lower(), self.prompt.strip(), str(self.variant)])
        return hashlib.sha256(text.encode()).hexdigest()[:24]

    @property
    def extension(self) -> str:
        return "png" if self.kind in ("image", "infographic") else "mp4"


def cache_path(course_id: int, request: VisualRequest) -> str:
    return f"courses/{course_id}/visuals/{request.key()}.{request.extension}"


@dataclass
class ClipStatus:
    done: bool
    uri: str | None = None
    error: str | None = None


@contextmanager
def _network(action: str):
    try:
        yield
    except httpx.HTTPError as exc:
        logger.warning("visual_provider_unreachable", extra={"action": action, "error_type": type(exc).__name__})
        raise VisualError(f"No pudimos {action}.") from exc


def _json(response: httpx.Response, action: str) -> dict:
    """A provider's JSON answer; anything else is a failed visual, not a crash."""
    try:
        body = response.json()
    except ValueError as exc:
        raise VisualError(f"Respuesta inesperada al {action}.") from exc
    if not isinstance(body, dict):
        raise VisualError(f"Respuesta inesperada al {action}.")
    return body


def _allowed(url: str) -> bool:
    parts = urlsplit(url)
    host = (parts.hostname or "").lower()
    return parts.scheme == "https" and any(host == domain or host.endswith("." + domain) for domain in DOWNLOAD_DOMAINS)


def _keywords(text: str) -> set[str]:
    return {word for word in re.findall(r"[a-z]+", text.lower()) if len(word) > 2}


class Visuals:
    """The real providers; each method raises VisualError when its kind can't be had."""

    def __init__(self, pixabay_key: str, openai_key: str, image_model: str, gemini_key: str, veo_model: str,
                 client: httpx.Client | None = None):
        # Redirects are followed by hand (`_download`): only to the providers' hosts, and the Gemini key never
        # leaves Gemini's own host.
        self.client = client or httpx.Client(timeout=REQUEST_TIMEOUT_SECONDS, follow_redirects=False)
        self.pixabay_key, self.openai_key, self.image_model = pixabay_key, openai_key, image_model
        self.gemini_key, self.veo_model = gemini_key, veo_model

    def available(self) -> set[Kind]:
        return {kind for kind, key in (("stock", self.pixabay_key), ("image", self.openai_key),
                                       ("infographic", self.openai_key), ("clip", self.gemini_key)) if key}

    # ── Stock (Pixabay) ──

    def stock(self, query: str, dest: Path) -> Path:
        """The best matching landscape video (or photo, saved as PNG) for `query`. Returns the file written."""
        if not self.pixabay_key:
            raise VisualError("No hay banco de videos configurado.")
        wanted = _keywords(query)
        with _network("buscar el video de stock"):
            response = self.client.get(f"{PIXABAY}/videos/", params={
                "key": self.pixabay_key, "q": query[:100], "per_page": 20, "safesearch": "true",
            })
        hits = _json(response, "buscar el video de stock").get("hits") if response.is_success else []
        for hit in hits or []:
            if not isinstance(hit, dict) or hit.get("duration", 0) < MIN_STOCK_SECONDS:
                continue
            if not wanted & _keywords(str(hit.get("tags", ""))):
                continue
            video = _stock_rendition(hit.get("videos") or {})
            if video:
                target = dest.with_suffix(".mp4")
                self._download(video["url"], target, "descargar el video de stock")
                return target
        with _network("buscar la foto de stock"):
            response = self.client.get(PIXABAY + "/", params={
                "key": self.pixabay_key, "q": query[:100], "image_type": "photo", "orientation": "horizontal",
                "min_width": 1600, "per_page": 20, "safesearch": "true",
            })
        hits = _json(response, "buscar la foto de stock").get("hits") if response.is_success else []
        for hit in hits or []:
            if isinstance(hit, dict) and wanted & _keywords(str(hit.get("tags", ""))) and hit.get("largeImageURL"):
                raw = dest.with_suffix(".jpg")
                self._download(hit["largeImageURL"], raw, "descargar la foto de stock")
                target = dest.with_suffix(".png")
                _to_png(raw, target)
                return target
        raise VisualError(f"No encontramos stock para «{query}».")

    # ── Generated image (OpenAI) ──

    def image(self, prompt: str, dest: Path) -> Path:
        return self._generate(f"{prompt.strip()} {STYLE}", "medium", dest)

    def infographic(self, prompt: str, dest: Path) -> Path:
        return self._generate(f"{prompt.strip()}\n\n{INFOGRAPHIC_STYLE}", "high", dest)

    def _generate(self, prompt: str, quality: str, dest: Path) -> Path:
        if not self.openai_key:
            raise VisualError("No hay generador de imágenes configurado.")
        with _network("generar la imagen"):
            response = self.client.post(OPENAI_IMAGES, timeout=IMAGE_TIMEOUT_SECONDS, headers={
                "Authorization": f"Bearer {self.openai_key}"}, json={
                "model": self.image_model, "prompt": prompt, "size": "1536x1024", "quality": quality, "n": 1,
            })
        if not response.is_success:
            logger.error("visual_image_failed", extra={"status": response.status_code, "detail": response.text[:300]})
            busy = response.status_code == 429 or response.status_code >= 500
            raise VisualError("No pudimos generar la imagen.", retryable=busy)
        try:
            image = base64.b64decode(_json(response, "generar la imagen")["data"][0]["b64_json"])
        except (KeyError, IndexError, TypeError, binascii.Error) as exc:
            raise VisualError("El generador de imágenes respondió algo inesperado.") from exc
        dest = dest.with_suffix(".png")
        dest.write_bytes(image)
        return dest

    # ── Animated clip (Google Veo) ──

    def start_clip(self, prompt: str) -> str:
        """Ask Veo for a clip; returns the operation to follow."""
        if not self.gemini_key:
            raise VisualError("No hay generador de clips configurado.")
        with _network("pedir el clip animado"):
            response = self.client.post(
                f"{GEMINI}/models/{self.veo_model}:predictLongRunning", headers={"x-goog-api-key": self.gemini_key},
                json={"instances": [{"prompt": f"{prompt.strip()} {STYLE}"}],
                      "parameters": {"aspectRatio": "16:9", "durationSeconds": CLIP_SECONDS}},
            )
        if not response.is_success:
            logger.error("visual_clip_failed", extra={"status": response.status_code, "detail": response.text[:300]})
            busy = response.status_code == 429 or response.status_code >= 500  # e.g. Veo's requests-per-minute limit
            raise VisualError("No pudimos pedir el clip animado.", retryable=busy)
        name = _json(response, "pedir el clip animado").get("name")
        if not isinstance(name, str) or not name.startswith("models/"):
            raise VisualError("Veo respondió algo inesperado.")
        return name

    def clip_status(self, operation: str) -> ClipStatus:
        """Veo's progress on a clip. A busy or unreachable Veo is retryable: the clip is paid for already."""
        try:
            response = self.client.get(f"{GEMINI}/{operation}", headers={"x-goog-api-key": self.gemini_key})
        except httpx.HTTPError as exc:
            raise VisualError("No pudimos consultar el clip animado.", retryable=True) from exc
        if not response.is_success:
            busy = response.status_code == 429 or response.status_code >= 500
            raise VisualError("No pudimos consultar el clip animado.", retryable=busy)
        body = _json(response, "consultar el clip animado")
        if not body.get("done"):
            return ClipStatus(done=False)
        if body.get("error"):
            error = body["error"]
            return ClipStatus(done=True, error=str(error.get("message", "error") if isinstance(error, dict) else error)[:200])
        try:
            result = body.get("response") or {}
            samples = (result.get("generateVideoResponse") or {}).get("generatedSamples") or result.get("generatedVideos")
            uri = samples[0]["video"]["uri"] if samples else None
        except (KeyError, IndexError, TypeError, AttributeError) as exc:
            raise VisualError("Veo respondió algo inesperado.") from exc
        if not isinstance(uri, str):  # e.g. filtered by Veo's safety rules
            return ClipStatus(done=True, error="Veo no devolvió el clip.")
        return ClipStatus(done=True, uri=uri)

    def download_clip(self, uri: str, dest: Path) -> Path:
        if urlsplit(uri).hostname != GEMINI_HOST:
            raise VisualError("El clip vino de un origen no esperado.")
        dest = dest.with_suffix(".mp4")
        self._download(uri, dest, "descargar el clip animado")
        return dest

    def _download(self, url: str, dest: Path, action: str) -> None:
        """Stream `url` to `dest`: https only, from the providers' hosts (also after each redirect), at most
        MAX_VISUAL_BYTES, and the Gemini key only ever sent to Gemini's host."""
        for _ in range(MAX_REDIRECTS + 1):
            if not _allowed(url):
                raise VisualError(f"No pudimos {action}: origen no permitido.")
            headers = {"x-goog-api-key": self.gemini_key} if urlsplit(url).hostname == GEMINI_HOST else {}
            with _network(action), self.client.stream("GET", url, headers=headers,
                                                      timeout=TRANSFER_TIMEOUT_SECONDS) as response:
                if response.is_redirect:
                    url = urljoin(url, response.headers.get("location", ""))
                    continue
                if response.is_error:
                    raise VisualError(f"No pudimos {action} ({response.status_code}).",
                                      retryable=response.status_code == 429 or response.status_code >= 500)
                if int(response.headers.get("content-length") or 0) > MAX_VISUAL_BYTES:
                    raise VisualError(f"No pudimos {action}: el archivo es demasiado grande.")
                written = 0
                with dest.open("wb") as fh:
                    for chunk in response.iter_bytes(CHUNK_BYTES):
                        written += len(chunk)
                        if written > MAX_VISUAL_BYTES:
                            raise VisualError(f"No pudimos {action}: el archivo es demasiado grande.")
                        fh.write(chunk)
                return
        raise VisualError(f"No pudimos {action}: demasiadas redirecciones.")


def _stock_rendition(videos: dict) -> dict | None:
    """Pixabay's Full HD rendition of a landscape video (its 4K one is far heavier for a 1080p video)."""
    for size in ("medium", "large"):
        video = videos.get(size) or {}
        width, height = video.get("width") or 0, video.get("height") or 0
        if isinstance(video.get("url"), str) and 1280 <= width <= 1920 and width >= height:
            return video
    return None


def _to_png(source: Path, dest: Path) -> None:
    from PIL import Image, UnidentifiedImageError

    try:
        with Image.open(source) as image:
            image.convert("RGB").save(dest)
    except (UnidentifiedImageError, OSError) as exc:
        raise VisualError("La foto de stock no se pudo leer.") from exc


class FakeVisuals:
    """Offline visuals for development and tests: colored test clips and images, made instantly."""

    def available(self) -> set[Kind]:
        return set(KINDS)

    def stock(self, query: str, dest: Path) -> Path:
        return _test_clip(dest.with_suffix(".mp4"), 6, "testsrc2")

    def image(self, prompt: str, dest: Path) -> Path:
        from PIL import Image

        dest = dest.with_suffix(".png")
        Image.new("RGB", (1536, 1024), (40, 90, 140)).save(dest)
        return dest

    def infographic(self, prompt: str, dest: Path) -> Path:
        from PIL import Image, ImageDraw

        dest = dest.with_suffix(".png")
        image = Image.new("RGB", (1536, 1024), (17, 17, 17))
        draw = ImageDraw.Draw(image)
        for n in range(3):  # three panels, like a comparison infographic
            draw.rectangle([90 + n * 470, 220, 470 + n * 470, 760], outline=(255, 76, 1), width=10)
        dest.parent.mkdir(parents=True, exist_ok=True)
        image.save(dest)
        return dest

    def start_clip(self, prompt: str) -> str:
        return f"fake-operation/{hashlib.sha256(prompt.encode()).hexdigest()[:12]}"

    def clip_status(self, operation: str) -> ClipStatus:
        return ClipStatus(done=True, uri=operation)

    def download_clip(self, uri: str, dest: Path) -> Path:
        return _test_clip(dest.with_suffix(".mp4"), CLIP_SECONDS, "smptebars")


def _test_clip(dest: Path, seconds: int, pattern: str) -> Path:
    subprocess.run(["ffmpeg", "-nostdin", "-y", "-loglevel", "error", "-f", "lavfi", "-i",
                    f"{pattern}=size=1280x720:rate=30:duration={seconds}", "-pix_fmt", "yuv420p", str(dest)],
                   check=True, capture_output=True)
    return dest


@lru_cache
def get_visuals() -> Visuals | FakeVisuals:
    settings = get_settings()
    if settings.use_fake_providers:
        return FakeVisuals()
    return Visuals(settings.pixabay_api_key, settings.openai_api_key, settings.openai_image_model,
                   settings.gemini_api_key, settings.veo_model)
