"""Icons a slide can show: a curated subset of Lucide (ISC license, see icons/LICENSE-lucide.txt).

The same names are lucide-react components in the editor (kebab-case here, PascalCase there). The font in
icons/Lucide.ttf only carries these glyphs; regenerate it with pyftsubset when the list changes.
"""

from pathlib import Path
from typing import Literal

ICON_FONT = Path(__file__).resolve().parent / "icons" / "Lucide.ttf"

ICONS: dict[str, int] = {
    "activity": 0xE038,
    "alarm-clock": 0xE03A,
    "arrow-right": 0xE049,
    "badge-check": 0xE241,
    "ban": 0xE051,
    "book-open": 0xE05F,
    "brain": 0xE3C6,
    "building-2": 0xE290,
    "calendar": 0xE063,
    "chart-bar": 0xE2A2,
    "chart-line": 0xE2A5,
    "chart-pie": 0xE06B,
    "check": 0xE06C,
    "circle-alert": 0xE077,
    "circle-check": 0xE226,
    "circle-x": 0xE084,
    "clipboard-check": 0xE219,
    "clipboard-list": 0xE086,
    "clock": 0xE087,
    "cog": 0xE30B,
    "coins": 0xE097,
    "compass": 0xE09B,
    "cross": 0xE1E5,
    "dollar-sign": 0xE0B1,
    "droplets": 0xE0B5,
    "ear": 0xE382,
    "eye": 0xE0BA,
    "eye-off": 0xE0BB,
    "factory": 0xE29F,
    "file-text": 0xE0CC,
    "flag": 0xE0D1,
    "flame": 0xE0D2,
    "forklift": 0xE3C1,
    "frown": 0xE0DB,
    "glasses": 0xE20D,
    "globe": 0xE0E8,
    "graduation-cap": 0xE234,
    "hammer": 0xE0EC,
    "hand": 0xE1D7,
    "hand-heart": 0xE5B9,
    "handshake": 0xE5C0,
    "hard-hat": 0xE0EE,
    "heart-handshake": 0xE2D7,
    "heart-pulse": 0xE36E,
    "hourglass": 0xE296,
    "house": 0xE0F5,
    "key": 0xE0FD,
    "layers": 0xE529,
    "leaf": 0xE2DE,
    "lightbulb": 0xE1C2,
    "link": 0xE102,
    "list-checks": 0xE1D0,
    "lock": 0xE10B,
    "mail": 0xE10F,
    "map-pin": 0xE111,
    "megaphone": 0xE235,
    "meh": 0xE114,
    "message-circle": 0xE116,
    "messages-square": 0xE40D,
    "notebook-pen": 0xE596,
    "octagon-alert": 0xE127,
    "package": 0xE129,
    "percent": 0xE132,
    "phone": 0xE133,
    "pill": 0xE3BD,
    "puzzle": 0xE29C,
    "receipt": 0xE3D3,
    "recycle": 0xE2E9,
    "refresh-cw": 0xE145,
    "repeat": 0xE146,
    "rocket": 0xE286,
    "scan-face": 0xE371,
    "search": 0xE151,
    "settings": 0xE154,
    "shield": 0xE158,
    "shield-check": 0xE1FF,
    "shopping-cart": 0xE15C,
    "siren": 0xE2EF,
    "smile": 0xE164,
    "sparkles": 0xE412,
    "star": 0xE176,
    "stethoscope": 0xE2F1,
    "store": 0xE3E4,
    "sun": 0xE178,
    "target": 0xE180,
    "thermometer": 0xE186,
    "thumbs-down": 0xE189,
    "thumbs-up": 0xE18A,
    "timer": 0xE1E0,
    "trending-down": 0xE190,
    "trending-up": 0xE191,
    "triangle-alert": 0xE193,
    "trophy": 0xE373,
    "truck": 0xE194,
    "user": 0xE19F,
    "user-check": 0xE1A0,
    "users": 0xE1A4,
    "wallet": 0xE204,
    "warehouse": 0xE3E6,
    "wind": 0xE1B0,
    "wrench": 0xE1B1,
    "x": 0xE1B2,
    "zap": 0xE1B4,
}

IconName = Literal[
    "activity",
    "alarm-clock",
    "arrow-right",
    "badge-check",
    "ban",
    "book-open",
    "brain",
    "building-2",
    "calendar",
    "chart-bar",
    "chart-line",
    "chart-pie",
    "check",
    "circle-alert",
    "circle-check",
    "circle-x",
    "clipboard-check",
    "clipboard-list",
    "clock",
    "cog",
    "coins",
    "compass",
    "cross",
    "dollar-sign",
    "droplets",
    "ear",
    "eye",
    "eye-off",
    "factory",
    "file-text",
    "flag",
    "flame",
    "forklift",
    "frown",
    "glasses",
    "globe",
    "graduation-cap",
    "hammer",
    "hand",
    "hand-heart",
    "handshake",
    "hard-hat",
    "heart-handshake",
    "heart-pulse",
    "hourglass",
    "house",
    "key",
    "layers",
    "leaf",
    "lightbulb",
    "link",
    "list-checks",
    "lock",
    "mail",
    "map-pin",
    "megaphone",
    "meh",
    "message-circle",
    "messages-square",
    "notebook-pen",
    "octagon-alert",
    "package",
    "percent",
    "phone",
    "pill",
    "puzzle",
    "receipt",
    "recycle",
    "refresh-cw",
    "repeat",
    "rocket",
    "scan-face",
    "search",
    "settings",
    "shield",
    "shield-check",
    "shopping-cart",
    "siren",
    "smile",
    "sparkles",
    "star",
    "stethoscope",
    "store",
    "sun",
    "target",
    "thermometer",
    "thumbs-down",
    "thumbs-up",
    "timer",
    "trending-down",
    "trending-up",
    "triangle-alert",
    "trophy",
    "truck",
    "user",
    "user-check",
    "users",
    "wallet",
    "warehouse",
    "wind",
    "wrench",
    "x",
    "zap",
]

NoIcon = Literal[""]
